name: Android RASP Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK with RASP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DIVA repository
        uses: actions/checkout@v3

      - name: Clone Android RASP repository
        run: |
          git clone https://github.com/securevale/android-rasp.git
          mv android-rasp ./app/rasp  # Move o repositório inteiro para dentro do projeto

      - name: Inject RASP Code into MainActivity
        run: |
          chmod +x ./inject_rasp.sh
          ./inject_rasp.sh

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execution permissions
        run: chmod +x ./app/gradlew

      - name: Build APK
        working-directory: app
        run: ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DIVA-App
          path: app/build/outputs/apk/debug/app-debug.apk
