name: Android RASP Integration

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    name: Build APK with RASP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DIVA repository
        uses: actions/checkout@v3

      - name: Clone Android RASP repository
        run: |
          git clone https://github.com/securevale/android-rasp.git rasp
          mv rasp diva-apk-file/rasp  # Move o módulo para dentro do DIVA

      - name: Inject RASP Code into MainActivity
        run: |
          chmod +x diva-apk-file/inject_rasp.sh
          ./diva-apk-file/inject_rasp.sh

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execution permissions
        run: chmod +x ./gradlew

      - name: Build APK
        working-directory: diva-apk-file
        run: ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: DIVA-App
          path: diva-apk-file/app/build/outputs/apk/debug/app-debug.apk
